#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
bash $HOME/.config/polybar/launch.sh &
feh --bg-scale ~/Pictures/Dog.jpg

bspc monitor -d term www file dev edit 

bspc config border_width         0
bspc config window_gap          12
bspc config top_padding		35
#bspc config border_radius 	8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	     	      "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

# Sending to Desktops
bspc rule --add firefox			desktop='www' follow=on
bspc rule --add Alacritty		desktop='term' follow=on
bspc rule -add thunar			desktop='file' follow=on

